<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>TEST</title>
</head>
<body>
    <? foreach($data as $val):?>
        <p>Название: <?=$val["name"];?></p>
        <p>Часы работы: от <?=$val["bhour"]?> до <?=$val["ehour"]?></p>
        <p><strong><?=$val["isopen"]?></strong></p>
        <p><strong><?=$val["when"]?></strong></p>
    <?endforeach;?>
</body>
</html>